### PR TITLE
Dummy change to test PR review requirements

### PR DESCRIPTION
**Pull request by niclasgillberg**

### CODE REVIEW

**Comment by niclasgillberg** [comment]
@tr-hagfjall Could you test to approve with your personal account to see if it's possible to merge with only that approval?

**Comment by Hagfjall** [comment]
image
Great!

**Comment by tr-hagfjall** [comment]
But.... I see this from this account :thinking:
image

**Review by Hagfjall — APPROVED** [review]

**Comment by niclasgillberg** [comment]
@tr-hagfjall I have disabled the possibility to override and merge without approvals :+1: 
image

**Comment by niclasgillberg** [comment]
PR review settings seems to work fine. Merge is not possible until a user with write access to the repo approves, which is what we want.

**Pull request closed without merging**
