### PR TITLE
Remove coders group from code owner file

### PR DESCRIPTION
**Pull request by niclasgillberg**

### CODE REVIEW

**Review by Hagfjall — APPROVED** [review]

**Comment by tr-hagfjall** [comment]
@niclasgillberg @genne Should we allow anyone to approve the changes in this repo? I think not. 
See above with my private @Hagfjall account approved and it's now possible to merge. Meaning we might accidentally merge stuff on to this repo without an approval from any @jointrine/backend.

**Comment by genne** [comment]
> @niclasgillberg @genne Should we allow anyone to approve the changes in this repo? I think not.
> See above with my private @Hagfjall account approved and it's now possible to merge. Meaning we might accidentally merge stuff on to this repo without an approval from any @jointrine/backend.

Isn't there a way to limit it so that non-members can't approve? Otherwise I say it's low risk - i.e. it means any of us coders can get any PR through without approval, but that only means you can create a new NuGet package. To actually use the package a member needs to approve.

**Comment by tr-hagfjall** [comment]
> > @niclasgillberg @genne Should we allow anyone to approve the changes in this repo? I think not.
> > See above with my private @Hagfjall account approved and it's now possible to merge. Meaning we might accidentally merge stuff on to this repo without an approval from any @jointrine/backend.
> 
> Isn't there a way to limit it so that non-members can't approve? Otherwise I say it's low risk - i.e. it means any of us coders can get any PR through without approval, but that only means you can create a new NuGet package. To actually use the package a member needs to approve.

The risk is a bit higher since one single coder can also deploy/use the new (potentially malicious package) without any additional approval when dependabot creates a PR with the new version and the same coder that merged the changes here can approve + merge to master.

**Comment by niclasgillberg** [comment]
@tr-hagfjall Was the merge blocked before? I just enabled required review and now it's not possible to merge. Since this changes the code owner file it still sees jointrine/backend as code owner, so it's hard to see if your approval has any effect on the ability to merge.

**Comment by genne** [comment]
> @tr-hagfjall Was the merge blocked before? I just enabled required review and now it's not possible to merge. Since this changes the code owner file it still sees jointrine/backend as code owner, so it's hard to see if your approval has any effect on the ability to merge.

Now it looks good to me 👍 (i.e. merging is blocked)

**Comment by niclasgillberg** [comment]
> Now it looks good to me +1 (i.e. merging is blocked)

Yes, but the question is what happens when the code owner file is changed. Now it requires a review from jointrine/backend because those files are owner by that team. 

I propose that we merge this and create a dummy PR to test how it behaves. What do you say about that, @tr-hagfjall and @genne?

**Review by genne — APPROVED** [review]
Sounds good!

**Comment by tr-hagfjall** [comment]
Sounds good!

**Pull request merged**
